export const USER_ROLES = {
  ADMIN: "admin",
  LECTURER: "lecturer",
  STUDENT: "student",
  PENDING: "pending",
} as const

export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Lagos State University (LASU)",
  "Covenant University",
  "Babcock University",
  "Landmark University",
  "Redeemer's University",
  "Bowen University",
  "Lead City University",
  "Bells University of Technology",
  "Crawford University",
  "Elizade University",
  "Fountain University",
  "Igbinedion University",
  "Joseph Ayo Babalola University",
  "Kwara State University",
  "Ladoke Akintola University of Technology",
  "Mountain Top University",
  "Nile University of Nigeria",
  "Pan-Atlantic University",
  "Salem University",
  "Southwestern University",
  "Summit University",
  "Tai Solarin University of Education",
  "Wesley University",
  "Adeleke University",
  "Afe Babalola University",
  "Al-Hikmah University",
  "American University of Nigeria",
  "Ajayi Crowther University",
  "Baze University",
  "Bingham University",
  "Caleb University",
]

export const ENGINEERING_SUBJECTS = [
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Computer Engineering",
  "Petroleum Engineering",
  "Agricultural Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Engineering",
  "Mining Engineering",
  "Marine Engineering",
  "Aerospace Engineering",
  "Nuclear Engineering",
  "Systems Engineering",
  "Food Engineering",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Transportation Engineering",
  "Water Resources Engineering",
  "Power Systems Engineering",
  "Control Systems Engineering",
  "Electronics Engineering",
  "Telecommunications Engineering",
  "Software Engineering",
  "Network Engineering",
  "Cybersecurity Engineering",
  "Robotics Engineering",
  "Mechatronics Engineering",
  "Engineering Mathematics",
  "Engineering Physics",
  "Engineering Chemistry",
  "Engineering Drawing",
  "Thermodynamics",
  "Fluid Mechanics",
  "Strength of Materials",
  "Engineering Mechanics",
  "Circuit Analysis",
  "Digital Electronics",
  "Analog Electronics",
  "Microprocessors",
  "Embedded Systems",
  "Signal Processing",
  "Communication Systems",
  "Antenna Theory",
  "Electromagnetic Fields",
  "Power Electronics",
  "Machine Design",
  "Manufacturing Processes",
  "Quality Control",
  "Project Management",
  "Engineering Economics",
  "Professional Ethics",
]

export const ACADEMIC_LEVELS = [
  "100 Level",
  "200 Level",
  "300 Level",
  "400 Level",
  "500 Level",
  "Postgraduate",
  "Masters",
  "PhD",
]

export const DIFFICULTY_LEVELS = ["Beginner", "Intermediate", "Advanced", "Expert"]

export const QUESTION_STATUS = ["Open", "Answered", "Closed", "Under Review"]

export const CONTENT_TYPES = [
  "Video Lesson",
  "Live Session",
  "Tutorial",
  "Workshop",
  "Seminar",
  "Lab Session",
  "Project Review",
  "Exam Prep",
]

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "popular", label: "Most Popular" },
  { value: "rating", label: "Highest Rated" },
  { value: "views", label: "Most Viewed" },
  { value: "alphabetical", label: "A-Z" },
]

export const VIEW_MODES = [
  { value: "grid", label: "Grid View" },
  { value: "list", label: "List View" },
  { value: "card", label: "Card View" },
]

export const NOTIFICATION_TYPES = [
  "question_answered",
  "new_lesson",
  "assignment_due",
  "live_session",
  "achievement_unlocked",
  "system_update",
]

export const ACHIEVEMENT_TYPES = [
  "First Question",
  "Question Master",
  "Top Contributor",
  "Knowledge Seeker",
  "Video Watcher",
  "Course Completer",
  "Perfect Score",
  "Streak Master",
  "Community Helper",
  "Expert Level",
]
